// src/ui/BlockComponent.svelte
<script lang="ts">
  import type Block from '../composition/Block'
  import Section from '../composition/Section'
  import Pitch from '../Pitch'

  export let block: Block
  export let blockHeight: number
  export let selected: boolean
   
  function scrollTo(node: HTMLDivElement, selected: boolean) {
    return {
      update() {
        if (selected) {
          node.scrollIntoView({block: 'center'})
        }
      }
    }
  }
</script>

<div
  class='block' 
  class:selected 
  style='height: {blockHeight * block.computedDuration}rem' 
  use:scrollTo={selected}
  on:click
>
  {#if block.element instanceof Pitch}
    {block.element.octave} . {block.element.interval.toString()}
  {:else if block.element instanceof Section}
    {block.element.name}
  {/if}
  <div>{block.duration.toString()}</div>
</div>

<style>
  .block {
    display: flex;
    flex-direction: column;
    justify-content: space-evenly;
    align-items: center;
    white-space: nowrap;
    font-weight: bold;
    user-select: none;
    cursor: pointer;
    border-bottom: var(--border);
  }

  .block:last-child {
    border-bottom: none;
  }

  .block:hover {
    background: var(--hover);
  }

  .block:active {
    background: var(--active);
  }

  .selected {
    background: var(--selected) !important;
  }
</style>

// src/ui/BlockComponent.tsx
import { forwardRef, MouseEventHandler } from 'react'
import Block from '../composition/Block'
import { cls } from '../util'
import style from './BlockComponent.module.css'
import common from './common.module.css'
import Pitch from '../Pitch'
import Section from '../composition/Section'

type Props = {
  block: Block,
  blockHeight: number,
  isSelected: boolean,
  onClick: MouseEventHandler
}

export default forwardRef<HTMLDivElement, Props>((props, ref) => {
  const { block } = props

  const divProps = {
    key: block.id,
    ref: ref,
    className: cls(style.block, props.isSelected && common.selected),
    style: {height: `${props.blockHeight * block.computedDuration}rem`},
    onClick: props.onClick,
  }

  return <div {...divProps}>
    {block.element instanceof Pitch && `${block.element.octave} . ${block.element.interval.toString()}`}
    {block.element instanceof Section && block.element.name}
    <div>{block.duration.toString()}</div>
  </div>
})
